apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: j6xo7a344-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: j6xo7a344-go 
  name: j6xo7a344-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: j6xo7a344-go 
